version: "3.9"
services:
  python:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    command: sleep infinity
    init: true
    env_file:
      - .env